### ISSUE TITLE
hw2 grading

### ISSUE THREAD

**Issue by sepkamal** [juansbr7/STAT545-hw01-Bonilla-Juan#2]
Hi Juan,

Good use of several different functions (str, names, length) to get an initial picture of the dataset. You can also try using nrow to get the number of rows directly. I liked that you showed a summary table of just 1 country.

Good use of select, filter, mutate, arrange, and pipe!

I'm not sure where the code is that created your first ggplot graph looking at columbia's gdpPercap, but it's a nice plot. Also nice idea to looks at the increments. I'm not familiar with function(x,y) {z<- x - y}, but I'm guessing you know what you're doing!

I liked how you clearly described what you were trying to do and what you learned from your graphs + tables. Nice use of colour in your plots. Your last plot in particular shows a strong level of understanding of several ggplot features. What were you trying to show with the line? Could maybe have a separate line for each country.

Repo was organized, though I didn't see an hw2 issue so I just made one. Also you could add a bit more reflection on what was easy/hard during for the assignment!

Cheers,
Sep

**Comment by cindyhurtado** [comment]
Cindy's Peer-review

Hi Juan,

I think overall you did a good job, putting colors and several sizes in your graphs. However, I didnt find the exploration of the qualitative varible nor the reflection on what was hard, easy. Although, you did mention that you are still working on how to interpret some graphs.
